### ISSUE TITLE
ImagePullBackoff with helm chart 0.1.24

### ISSUE THREAD

**Issue by toriath** [brainfair/flux2-bitbucketpipeline-dispatcher#18]
Hello there,

I've tried installing the bpdispatcher to a demo flux setup an I recieve an ImagePullBackOff error.

Here's the description of my pod.

`Name:             bpdispatcher-5c5bc9fc7f-kzgrj
Namespace:        flux-system
Priority:         0
Service Account:  bpdispatcher
Node:             flux-hub-control-plane/172.18.0.2
Start Time:       Mon, 02 Sep 2024 14:07:57 +0200
Labels:           app.kubernetes.io/instance=bpdispatcher
                  app.kubernetes.io/name=bpdispatcher
                  pod-template-hash=5c5bc9fc7f
Annotations:      checksum/secret: e186e0b2ca868a8e753606765d48290d79acf4b88c7f65162a0621da8f45181d
Status:           Pending
IP:               10.244.0.42
IPs:
  IP:           10.244.0.42
Controlled By:  ReplicaSet/bpdispatcher-5c5bc9fc7f
Containers:
  bpdispatcher:
    Container ID:   
    Image:          brainfair/bpdispatcher:v0.0.29
    Image ID:       
    Port:           8000/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Liveness:       http-get http://:http/healthz delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get http://:http/ready delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment Variables from:
      bpdispatcher-secret  Secret  Optional: false
    Environment:           <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-n4w6p (ro)
Conditions:
  Type                        Status
  PodReadyToStartContainers   True 
  Initialized                 True 
  Ready                       False 
  ContainersReady             False 
  PodScheduled                True 
Volumes:
  kube-api-access-n4w6p:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  10m                  default-scheduler  Successfully assigned flux-system/bpdispatcher-5c5bc9fc7f-kzgrj to flux-hub-control-plane
  Normal   Pulling    9m17s (x4 over 10m)  kubelet            Pulling image "brainfair/bpdispatcher:v0.0.29"
  Warning  Failed     9m15s (x4 over 10m)  kubelet            Failed to pull image "brainfair/bpdispatcher:v0.0.29": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/brainfair/bpdispatcher:v0.0.29": no match for platform in manifest: not found
  Warning  Failed     9m15s (x4 over 10m)  kubelet            Error: ErrImagePull
  Warning  Failed     9m4s (x6 over 10m)   kubelet            Error: ImagePullBackOff
  Normal   BackOff    50s (x42 over 10m)   kubelet            Back-off pulling image "brainfair/bpdispatcher:v0.0.29"
`

**Comment by brainfair** [comment]
Hi @toriath, I guess you are trying to run it on an ARM instance. Currently, only Linux/AMD64 images are available.

**Comment by brainfair** [comment]
I have added the ARM build, try the latest version now (0.1.25) with image v0.0.30
